# Pull the Node image from Docker Hub
FROM node:16-alpine

# Setting Working Directory
#WORKDIR "C:\\www\\my-wallets\\frontend"
WORKDIR "/usr/app"

# Copying only package.json
COPY package*.json ./

# Copy rest of the code to container
COPY . .
COPY ../common ../common

# Install Dependencies
RUN npm install

EXPOSE 3000

# Run the React app
CMD ["npm", "start"]