version: "3.9"
services:

  # common:
  #  build:
  #     context: ./common
  #     dockerfile: Dockerfile.dev
  #  ports:
  #    - 3081:3081
  #  container_name: mern-common
  #  networks:
  #    - my-wallets-net
  #  volumes:
  #   - ./common/src:/usr/app/src
  #  depends_on:
  #   - db

  frontend:
   build:
      context: ./
      dockerfile: ./frontend/Dockerfile.dev
   image: wallets-frontend:lastest
   ports:
    -  3000:3000
   container_name: my-wallets-frontend
   networks:
    -  my-wallets-net
   volumes:
    -  ./frontend:/usr/app
    #-  ./frontend/public:/usr/app/public
    -  ./common:/usr/common
   depends_on:
    - backend
   stdin_open: true
   tty: true

  backend:
   build:
      context: ./
      dockerfile: ./backend/Dockerfile.dev
   image: wallets-backend:lastest
   ports:
     - 3001:3001
   container_name: my-wallets-backend
   networks:
     - my-wallets-net
   volumes:
    - ./backend:/usr/app
    - ./common:/usr/common
   depends_on:
    - db

  db:
    image: mongo
    ports:
      - 3017:27017
    container_name: mongo-db
    networks:
      - my-wallets-net
    volumes:
      - mongo-data:/data/db

networks:
  my-wallets-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local