# Pull the Node image from Docker Hub
FROM node:14-slim

# Setting Working Directory
#WORKDIR "C:\\www\\my-wallets\\backend"
WORKDIR "/usr/app"

# Copying only package.json
COPY package*.json ./

# Install Dependencies
RUN npm install

# Seed database
RUN npm run seed

# Copy rest of the code to container
COPY . .
COPY common ../common

EXPOSE 3001

# Run the API on Nodemon
CMD ["npm", "run", "start:dev"]
